FROM node:24

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY auth/package*.json ./

USER node

RUN npm install

COPY --chown=node:node auth/ .

EXPOSE 3000

CMD [ "node", "app.js" ]